# !/bin/bash
# set -e
# set -x

#pip install -r requirements.txt

# Note -- these are not the recommended settings for this dataset.  This is just so the open-source tests will finish quickly.

############## Preprecess the dataset
# python main.py --preprocess-dataset --ssample-input-size 1 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl'

#######################################################################################################
###################################            First test           ###################################
#######################################################################################################

#python main.py --train --num-components 20 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_1" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_1_final_W.pkl' --H-name 'triUMPF_1_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_1" --model-name "triUMPF_1" --batch 50 --num-jobs 15
#
#python main.py --train --num-components 50 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_2" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_2_final_W.pkl' --H-name 'triUMPF_2_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_2" --model-name "triUMPF_2" --batch 50 --num-jobs 15
#
#python main.py --train --num-components 70 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_3" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_3_final_W.pkl' --H-name 'triUMPF_3_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_3" --model-name "triUMPF_3" --batch 50 --num-jobs 15
#
#python main.py --train --num-components 90 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_4" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_4_final_W.pkl' --H-name 'triUMPF_4_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_4" --model-name "triUMPF_4" --batch 50 --num-jobs 15
#
#python main.py --train --num-components 120 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_5" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_5_final_W.pkl' --H-name 'triUMPF_5_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_5" --model-name "triUMPF_5" --batch 50 --num-jobs 15

#######################################################################################################
###################################           Second test           ###################################
#######################################################################################################

#python main.py --train --fit-features --num-components 20 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_6" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_6_final_W.pkl' --H-name 'triUMPF_6_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_6" --model-name "triUMPF_6" --batch 50 --num-jobs 15
#
#python main.py --train --fit-features --num-components 50 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_7" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_7_final_W.pkl' --H-name 'triUMPF_7_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_7" --model-name "triUMPF_7" --batch 50 --num-jobs 15
#
#python main.py --train --fit-features --num-components 70 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_8" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_8_final_W.pkl' --H-name 'triUMPF_8_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_8" --model-name "triUMPF_8" --batch 50 --num-jobs 15
#
#python main.py --train --fit-features --num-components 90 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_9" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_9_final_W.pkl' --H-name 'triUMPF_9_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_9" --model-name "triUMPF_9" --batch 50 --num-jobs 15
#
#python main.py --train --fit-features --num-components 120 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_10" --batch 50 --max-inner-iter 5 --num-epochs 100 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_10_final_W.pkl' --H-name 'triUMPF_10_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_10" --model-name "triUMPF_10" --batch 50 --num-jobs 15

#######################################################################################################
###################################            Third test           ###################################
#######################################################################################################

## best result
#python main.py --train --fit-features --binarize --num-components 100 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_11" --batch 50 --max-inner-iter 5 --num-epochs 50 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_11" --model-name "triUMPF_11" --batch 50 --num-jobs 15

#######################################################################################################
###################################           Fourth test           ###################################
#######################################################################################################

#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 20 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_12" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_12" --model-name "triUMPF_12_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 50 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_13" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_13" --model-name "triUMPF_13_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 70 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_14" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_14" --model-name "triUMPF_14_final" --batch 50 --num-jobs 15
#
## best result
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_15" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_15" --model-name "triUMPF_15_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 100 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_16" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_16" --model-name "triUMPF_16_final" --batch 50 --num-jobs 15

#######################################################################################################
###################################            Fifth test           ###################################
#######################################################################################################

#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 20 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_17" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_17" --model-name "triUMPF_17_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 50 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_18" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_18" --model-name "triUMPF_18_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 70 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_19" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_19" --model-name "triUMPF_19_final" --batch 50 --num-jobs 15
#
## best result
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_20" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_20" --model-name "triUMPF_20_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_21" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_21" --model-name "triUMPF_21_final" --batch 50 --num-jobs 15

#######################################################################################################
###################################            Sixth test           ###################################
#######################################################################################################

#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.2 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_22" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_22" --model-name "triUMPF_22_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 1 --proxy-order-e 1 --mu-omega 0.3 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_23" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_23" --model-name "triUMPF_23_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 2 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_24" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_24" --model-name "triUMPF_24_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 2 --proxy-order-e 1 --mu-omega 0.2 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_25" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_25" --model-name "triUMPF_25_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 2 --proxy-order-e 1 --mu-omega 0.3 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_26" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_26" --model-name "triUMPF_26_final" --batch 50 --num-jobs 15
#
## best result
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_27" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_27" --model-name "triUMPF_27_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.2 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_28" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_28" --model-name "triUMPF_28_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.3 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_29" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_29" --model-name "triUMPF_29_final" --batch 50 --num-jobs 15

#######################################################################################################
###################################          Seventh test           ###################################
#######################################################################################################

#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_30" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_30" --model-name "triUMPF_30_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.2 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_31" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_31" --model-name "triUMPF_31_final" --batch 50 --num-jobs 15
#
## best result
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_32" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_32" --model-name "triUMPF_32_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 2 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_33" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_33" --model-name "triUMPF_33_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 2 --mu-omega 0.1 --mu-gamma 0.2 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_34" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_34" --model-name "triUMPF_34_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 2 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_35" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_35" --model-name "triUMPF_35_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 3 --mu-omega 0.1 --mu-gamma 0.1 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_36" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_36" --model-name "triUMPF_36_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 3 --mu-omega 0.1 --mu-gamma 0.2 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_37" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_37" --model-name "triUMPF_37_final" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 3 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_38" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_38" --model-name "triUMPF_38_final" --batch 50 --num-jobs 15

#######################################################################################################
###################################            Tenth test           ###################################
#######################################################################################################

# preprocessing dataset
#python main.py --preprocess-dataset --ssample-input-size 0.2 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_2.pkl"
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_44" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_44_final_W.pkl' --H-name 'triUMPF_44_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_44" --model-name "triUMPF_44" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_45" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_45_final_W.pkl' --H-name 'triUMPF_45_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_45" --model-name "triUMPF_45" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_46" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_46_final_W.pkl' --H-name 'triUMPF_46_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_46" --model-name "triUMPF_46" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_47" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_47_final_W.pkl' --H-name 'triUMPF_47_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_47" --model-name "triUMPF_47" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_48" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_48_final_W.pkl' --H-name 'triUMPF_48_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_48" --model-name "triUMPF_48" --batch 50 --num-jobs 15

# preprocessing dataset
#python main.py --preprocess-dataset --ssample-input-size 0.4 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_4.pkl"
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_54" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_54_final_W.pkl' --H-name 'triUMPF_54_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_54" --model-name "triUMPF_54" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_55" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_55_final_W.pkl' --H-name 'triUMPF_55_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_55" --model-name "triUMPF_55" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_56" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_56_final_W.pkl' --H-name 'triUMPF_56_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_56" --model-name "triUMPF_56" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_57" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_57_final_W.pkl' --H-name 'triUMPF_57_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_57" --model-name "triUMPF_57" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_58" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_58_final_W.pkl' --H-name 'triUMPF_58_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_58" --model-name "triUMPF_58" --batch 50 --num-jobs 15

# preprocessing dataset
#python main.py --preprocess-dataset --ssample-input-size 0.6 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_6.pkl"
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_64" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_64_final_W.pkl' --H-name 'triUMPF_64_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_64" --model-name "triUMPF_64" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_65" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_65_final_W.pkl' --H-name 'triUMPF_65_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_65" --model-name "triUMPF_65" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_66" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_66_final_W.pkl' --H-name 'triUMPF_66_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_66" --model-name "triUMPF_66" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_67" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_67_final_W.pkl' --H-name 'triUMPF_67_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_67" --model-name "triUMPF_67" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_68" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_68_final_W.pkl' --H-name 'triUMPF_68_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_68" --model-name "triUMPF_68" --batch 50 --num-jobs 15

# preprocessing dataset
#python main.py --preprocess-dataset --ssample-input-size 0.8 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_8.pkl"
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_74" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_74_final_W.pkl' --H-name 'triUMPF_74_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_74" --model-name "triUMPF_74" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_75" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_75_final_W.pkl' --H-name 'triUMPF_75_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_75" --model-name "triUMPF_75" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_76" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_76_final_W.pkl' --H-name 'triUMPF_76_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_76" --model-name "triUMPF_76" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_77" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_77_final_W.pkl' --H-name 'triUMPF_77_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_77" --model-name "triUMPF_77" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_78" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_78_final_W.pkl' --H-name 'triUMPF_78_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_78" --model-name "triUMPF_78" --batch 50 --num-jobs 15

#######################################################################################################
###################################          Eleventh test          ###################################
#######################################################################################################

#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_79" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_79_final_W.pkl' --H-name 'triUMPF_79_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_79" --model-name "triUMPF_79" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_80" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_80_final_W.pkl' --H-name 'triUMPF_80_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_80" --model-name "triUMPF_80" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_81" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_81_final_W.pkl' --H-name 'triUMPF_81_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_81" --model-name "triUMPF_81" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_82" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_82_final_W.pkl' --H-name 'triUMPF_82_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_82" --model-name "triUMPF_82" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_2.pkl" --model-name "triUMPF_83" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_83_final_W.pkl' --H-name 'triUMPF_83_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_83" --model-name "triUMPF_83" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_84" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_84_final_W.pkl' --H-name 'triUMPF_84_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_84" --model-name "triUMPF_84" --batch 50 --num-jobs 15

#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_85" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_85_final_W.pkl' --H-name 'triUMPF_85_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_85" --model-name "triUMPF_85" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_86" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_86_final_W.pkl' --H-name 'triUMPF_86_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_86" --model-name "triUMPF_86" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_87" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_87_final_W.pkl' --H-name 'triUMPF_87_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_87" --model-name "triUMPF_87" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_4.pkl" --model-name "triUMPF_88" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_88_final_W.pkl' --H-name 'triUMPF_88_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_88" --model-name "triUMPF_88" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_89" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_89_final_W.pkl' --H-name 'triUMPF_89_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_89" --model-name "triUMPF_89" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_90" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_90_final_W.pkl' --H-name 'triUMPF_90_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_90" --model-name "triUMPF_90" --batch 50 --num-jobs 15

#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_91" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_91_final_W.pkl' --H-name 'triUMPF_91_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_91" --model-name "triUMPF_91" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_92" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_92_final_W.pkl' --H-name 'triUMPF_92_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_92" --model-name "triUMPF_92" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_6.pkl" --model-name "triUMPF_93" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_93_final_W.pkl' --H-name 'triUMPF_93_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_93" --model-name "triUMPF_93" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 20 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_94" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_94_final_W.pkl' --H-name 'triUMPF_94_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_94" --model-name "triUMPF_94" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 50 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_95" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_95_final_W.pkl' --H-name 'triUMPF_95_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_95" --model-name "triUMPF_95" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 70 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_96" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_96_final_W.pkl' --H-name 'triUMPF_96_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_96" --model-name "triUMPF_96" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 90 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_97" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_97_final_W.pkl' --H-name 'triUMPF_97_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_97" --model-name "triUMPF_97" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --M-name "M_8.pkl" --model-name "triUMPF_98" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_98_final_W.pkl' --H-name 'triUMPF_98_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_98" --model-name "triUMPF_98" --batch 50 --num-jobs 15

#######################################################################################################
###################################           Twelvth test          ###################################
#######################################################################################################

# preprocessing dataset
#python main.py --preprocess-dataset --white-links --ssample-input-size 0.2 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_2.pkl" --A-name "A_2.pkl" --B-name "B_2.pkl"
#
#python main.py --preprocess-dataset --white-links --ssample-input-size 0.4 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_4.pkl" --A-name "A_4.pkl" --B-name "B_4.pkl"
#
#python main.py --preprocess-dataset --white-links --ssample-input-size 0.6 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_6.pkl" --A-name "A_6.pkl" --B-name "B_6.pkl"
#
#python main.py --preprocess-dataset --white-links --ssample-input-size 0.8 --object-name "biocyc.pkl" --pathway2ec-name "pathway2ec.pkl" --pathway2ec-pidx-name 'pathway2ec_idx.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --hin-name 'hin_cmt.pkl' --M-name "M_8.pkl" --A-name "A_8.pkl" --B-name "B_8.pkl"

# train
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --A-name "A_2.pkl" --model-name "triUMPF_103" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_103_final_W.pkl' --H-name 'triUMPF_103_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_103" --model-name "triUMPF_103" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --A-name "A_4.pkl" --model-name "triUMPF_104" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_104_final_W.pkl' --H-name 'triUMPF_104_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_104" --model-name "triUMPF_104" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --A-name "A_6.pkl" --model-name "triUMPF_105" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_105_final_W.pkl' --H-name 'triUMPF_105_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_105" --model-name "triUMPF_105" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --A-name "A_8.pkl" --model-name "triUMPF_106" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_106_final_W.pkl' --H-name 'triUMPF_106_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_106" --model-name "triUMPF_106" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --B-name "B_2.pkl" --model-name "triUMPF_107" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_107_final_W.pkl' --H-name 'triUMPF_107_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_107" --model-name "triUMPF_107" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --B-name "B_4.pkl" --model-name "triUMPF_108" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_108_final_W.pkl' --H-name 'triUMPF_108_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_108" --model-name "triUMPF_108" --batch 50 --num-jobs 15

#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --B-name "B_6.pkl" --model-name "triUMPF_109" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_109_final_W.pkl' --H-name 'triUMPF_109_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_109" --model-name "triUMPF_109" --batch 50 --num-jobs 15
#
#python main.py --train --binarize --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.001 10 --ssample-input-size 0.05 --B-name "B_8.pkl" --model-name "triUMPF_110" --batch 50 --max-inner-iter 5 --num-epochs 5 --num-jobs 15
#python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_110_final_W.pkl' --H-name 'triUMPF_110_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_110" --model-name "triUMPF_110" --batch 50 --num-jobs 15

#######################################################################################################
###################################          Thirteen test          ###################################
#######################################################################################################

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 10 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_99" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_99" --model-name "triUMPF_99_final" --batch 50 --num-jobs 15

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 1 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_100" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_100" --model-name "triUMPF_100_final" --batch 50 --num-jobs 15
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.1 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_101" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_101" --model-name "triUMPF_101_final" --batch 50 --num-jobs 15

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.01 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_102" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_102" --model-name "triUMPF_102_final" --batch 50 --num-jobs 15

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_103" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_103" --model-name "triUMPF_103_final" --batch 50 --num-jobs 15

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --no-decomposition --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 90 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.0001 --ssample-input-size 0.05 --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_111" --batch 50 --max-inner-iter 5 --num-epochs 3 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'W.pkl' --H-name 'H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_111" --model-name "triUMPF_111_final" --batch 50 --num-jobs 15

# Final model
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_B" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_B_final_W.pkl' --H-name 'triUMPF_B_final_H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_B" --model-name "triUMPF_B_final" --batch 50 --num-jobs 15
#
# python main.py --train --binarize --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --model-name "triUMPF_O" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_O_final_W.pkl' --H-name 'triUMPF_O_final_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_O" --model-name "triUMPF_O_final" --batch 50 --num-jobs 15

# Combined model
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'combined_Xe.pkl' --y-name 'combined_y.pkl' --model-name "triUMPF_C" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_C_final_W.pkl' --H-name 'triUMPF_C_final_H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_C" --model-name "triUMPF_C_final" --batch 50 --num-jobs 15

# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 120 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'combined_Xe.pkl' --y-name 'combined_y.pkl' --M-name "M_8.pkl" --A-name "A_8.pkl" --B-name "B_8.pkl" --model-name "triUMPF_C1" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 15
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_C1_final_W.pkl' --H-name 'triUMPF_C1_final_H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_C1" --model-name "triUMPF_C1_final" --batch 50 --num-jobs 15

#################### predict
# python main.py --predict --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'symbionts_Xe.pkl' --file-name "triumpf_symbionts" --model-name "triumpf/triUMPF_B_final" --rsfolder "triUMPF_symbionts" --batch 50 --num-jobs 1
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triumpf/triUMPF_B_final_W.pkl' --H-name 'triumpf/triUMPF_B_final_H.pkl' --X-name 'symbionts_Xe.pkl' --y-name 'symbionts_y.pkl' --file-name "triUMPF_symbionts" --model-name "triumpf/triUMPF_B_final" --batch 50 --num-jobs 1
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triumpf/triUMPF_B_final_W.pkl' --H-name 'triumpf/triUMPF_B_final_H.pkl' --X-name 'hots_4_Xe.pkl' --y-name 'hots_4_y.pkl' --file-name "triUMPF_hots_4" --model-name "triumpf/triUMPF_B_final" --batch 50 --num-jobs 1
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triumpf/triUMPF_B_final_W.pkl' --H-name 'triumpf/triUMPF_B_final_H.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_cami" --model-name "triumpf/triUMPF_B_final" --batch 50 --num-jobs 1

#######################################################################################################
###################################          FINAL PUBLIC           ###################################
#######################################################################################################
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_X.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_X" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_X_W.pkl' --H-name 'triUMPF_X_H.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_X_1" --model-name "triUMPF_X" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_X_W.pkl' --H-name 'triUMPF_X_H.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_X_2" --model-name "triUMPF_X" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_X_W.pkl' --H-name 'triUMPF_X_H.pkl' --X-name 'sag_X.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_X_3" --model-name "triUMPF_X" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xe.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_e" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_e_W.pkl' --H-name 'triUMPF_e_H.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_e_1" --model-name "triUMPF_e" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_e_W.pkl' --H-name 'triUMPF_e_H.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_e_2" --model-name "triUMPF_e" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_e_W.pkl' --H-name 'triUMPF_e_H.pkl' --X-name 'sag_Xe.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_e_3" --model-name "triUMPF_e" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xa.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_a" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_a_W.pkl' --H-name 'triUMPF_a_H.pkl' --X-name 'golden_Xa.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_a_1" --model-name "triUMPF_a" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_a_W.pkl' --H-name 'triUMPF_a_H.pkl' --X-name 'cami_Xa.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_a_2" --model-name "triUMPF_a" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_a_W.pkl' --H-name 'triUMPF_a_H.pkl' --X-name 'sag_Xa.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_a_3" --model-name "triUMPF_a" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xc.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_c" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_c_W.pkl' --H-name 'triUMPF_c_H.pkl' --X-name 'golden_Xc.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_c_1" --model-name "triUMPF_c" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_c_W.pkl' --H-name 'triUMPF_c_H.pkl' --X-name 'cami_Xc.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_c_2" --model-name "triUMPF_c" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_c_W.pkl' --H-name 'triUMPF_c_H.pkl' --X-name 'sag_Xc.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_c_3" --model-name "triUMPF_c" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xea.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_ea" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ea_W.pkl' --H-name 'triUMPF_ea_H.pkl' --X-name 'golden_Xea.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_ea_1" --model-name "triUMPF_ea" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ea_W.pkl' --H-name 'triUMPF_ea_H.pkl' --X-name 'cami_Xea.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_ea_2" --model-name "triUMPF_ea" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ea_W.pkl' --H-name 'triUMPF_ea_H.pkl' --X-name 'sag_Xea.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_ea_3" --model-name "triUMPF_ea" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xec.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_ec" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ec_W.pkl' --H-name 'triUMPF_ec_H.pkl' --X-name 'golden_Xec.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_ec_1" --model-name "triUMPF_ec" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ec_W.pkl' --H-name 'triUMPF_ec_H.pkl' --X-name 'cami_Xec.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_ec_2" --model-name "triUMPF_ec" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_ec_W.pkl' --H-name 'triUMPF_ec_H.pkl' --X-name 'sag_Xec.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_ec_3" --model-name "triUMPF_ec" --batch 50 --num-jobs 20
#
# python main.py --train --binarize --use-external-features --fit-features --fit-comm --penalty 'l21' --num-components 100 --num-communities-p 90 --num-communities-e 100 --proxy-order-p 3 --proxy-order-e 1 --mu-omega 0.1 --mu-gamma 0.3 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --rho 0.001 --ssample-input-size 0.05 --X-name 'biocyc21_Xm.pkl' --y-name 'biocyc21_y.pkl' --model-name "triUMPF_m" --batch 50 --max-inner-iter 5 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_m_W.pkl' --H-name 'triUMPF_m_H.pkl' --X-name 'golden_Xm.pkl' --y-name 'golden_y.pkl' --file-name "triUMPF_m_1" --model-name "triUMPF_m" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_m_W.pkl' --H-name 'triUMPF_m_H.pkl' --X-name 'cami_Xm.pkl' --y-name 'cami_y.pkl' --file-name "triUMPF_m_2" --model-name "triUMPF_m" --batch 50 --num-jobs 20
# python main.py --evaluate --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --W-name 'triUMPF_m_W.pkl' --H-name 'triUMPF_m_H.pkl' --X-name 'sag_Xm.pkl' --y-name 'sag_y.pkl' --file-name "triUMPF_m_3" --model-name "triUMPF_m" --batch 50 --num-jobs 20

python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_X.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_X" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_X" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xe.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_e" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_E" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xa.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_a" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_A" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xc.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_c" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_C" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xea.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_ea" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_EA" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xec.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_ec" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_EC" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
python main.py --predict --pathway-report --no-parse --no-build-features --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xm.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "triUMPF_m" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "triUMPF_SAG_M" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
